environment:
  P: "c:/projects/libs"
  ACCOUNT:
      secure: F8Xu4syZJRRLmTnPDOUjr5bG7Lk6UburldIUuxZ/OJQ=
  PYTHON: "C:\\Python36-x64"
  PYTHON_VERSION: "3.6.x" # currently 3.6.0
  PYTHON_ARCH: "64"

# branches to build
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os: Visual Studio 2017

install:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\dev

platform: x64
configuration: Release

build_script:
  - call build_pyosmium_devpack.bat

artifacts:
  - path: pyosmium_libs_Release.7z
    name: pyosmium_libs_Release.7z

test: off

deploy_script:
  - cd c:\dev
  - curl -T pyosmium_libs_Release.7z --user %ACCOUNT% https://webdav.yandex.ru/libs/pyosmium_libs_Release.7z

